services:
  agoffice:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    ports:
      - "10002:8000"
    environment:
      PRODUCT_ENV: ${PRODUCT_ENV}
      CLIENT_ID: ${CLIENT_ID}
      STORAGE_SERVICE_URL : ${STORAGE_SERVICE_URL}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      #KEYCLOAK_AUDIENCE: ””
      SQL_TYPE: ${SQL_TYPE}
      SQL_HOST: ${SQL_HOST}
      SQL_PORT: ${SQL_PORT}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DB: ${SQL_DB}
      REDIS_URL: ${REDIS_URL}
      IMAGE_NAME_CODER_PRO: ${IMAGE_NAME_CODER_PRO}
      IMAGE_NAME_CODER_NOOB: ${IMAGE_NAME_CODER_NOOB}
      ROOM_RUNTIME_MODE: ${ROOM_RUNTIME_MODE}
      LOCAL_IMAGE_NAME_CODER_PRO: ${LOCAL_IMAGE_NAME_CODER_PRO}
      LOCAL_IMAGE_NAME_CODER_NOOB: ${LOCAL_IMAGE_NAME_CODER_NOOB}
      WORKER_BUILD_ID: ${WORKER_BUILD_ID}
      ROOM_REMOTE_CONFIG_PATH: ${ROOM_REMOTE_CONFIG_PATH}
      ROOM_K8S_NAMESPACE: ${ROOM_K8S_NAMESPACE}
      ROOM_K8S_STORAGE_CLASS: ${ROOM_K8S_STORAGE_CLASS}
      ROOM_K8S_PVC_SIZE: ${ROOM_K8S_PVC_SIZE}
      ROOM_SCHEDULING_TIMEOUT_SECONDS: ${ROOM_SCHEDULING_TIMEOUT_SECONDS}
      ROOM_WORKER_PORT: ${ROOM_WORKER_PORT}
      ROOM_WORKER_SOCKETIO_PATH: ${ROOM_WORKER_SOCKETIO_PATH}
      ROOM_NOOB_RUNTIME_CLASS: ${ROOM_NOOB_RUNTIME_CLASS}
      ROOM_NOOB_MOUNT_PATH: ${ROOM_NOOB_MOUNT_PATH}
      HATCHET_CLIENT_TOKEN: ${HATCHET_CLIENT_TOKEN}
      HATCHET_CLIENT_HOST_PORT: ${HATCHET_CLIENT_HOST_PORT}
      HATCHET_CLIENT_SERVER_URL: ${HATCHET_CLIENT_SERVER_URL}
      HATCHET_CLIENT_TLS_STRATEGY: "none"
      AGVIDEO_API_URL: ${AGVIDEO_API_URL}
      AGCORE_API_URL: ${AGCORE_API_URL}
      AGOFFICE_API_URL: ${AGOFFICE_API_URL}
